name: "Upload DirectCloud-Box"
author: "tk3fftk"
description: "Upload artifacts to DirectCloud-BOX from GitHub Actions"
branding:
  icon: "folder-plus"
  color: "blue"
runs:
  using: "node12"
  main: "dist/index.js"
